export const demoUsers = [
  {
    firstName: "David",
    lastName: "Paul",
    username: "davidpaul",
    gender: "male",
    dob: "1990-05-15",
    email: "davidpaul@test.com",
    password: "david1234",
    role: "admin",
  },
  {
    firstName: "John",
    lastName: "Doe",
    username: "johndoe",
    gender: "male",
    dob: "1990-05-15",
    email: "johndoe@example.com",
    password: "password123",
    role: "user",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    username: "janesmith",
    gender: "female",
    dob: "1985-10-25",
    email: "janesmith@example.com",
    password: "securepass",
    role: "user",
  },
  {
    firstName: "Alexa",
    lastName: "Johnson",
    username: "alexaj",
    gender: "female",
    dob: "1995-08-12",
    email: "alexa.johnson@example.com",
    password: "pass1234",
    role: "user",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    username: "emilydavis",
    gender: "female",
    dob: "1992-04-30",
    email: "emily.davis@example.com",
    password: "securepwd",
    role: "guest",
  },
  {
    firstName: "Rohit",
    lastName: "Singh",
    username: "rohitsingh",
    gender: "male",
    dob: "1990-04-30",
    email: "rohit.singh@example.com",
    password: "singhisking",
    role: "guest",
  },
];

export const demoGuests = [
  {
    firstName: "Michael",
    lastName: "Brown",
    username: "michaelb123",
    gender: "male",
    dob: "1980-09-25",
    email: "michael.brown@example.com",
    password: "strong_pass1",
    role: "guest",
  },
  {
    firstName: "Ria",
    lastName: "Martinez",
    username: "ria_90",
    gender: "female",
    dob: "1980-12-18",
    email: "emily.davis@example.com",
    password: "secure_pass2",
    role: "guest",
  },
  {
    firstName: "Christopher",
    lastName: "Martinez",
    username: "chrism77",
    gender: "male",
    dob: "1975-06-10",
    email: "christopher.martinez@example.com",
    password: "my_safe_pass",
    role: "guest",
  },
  {
    firstName: "Alexandra",
    lastName: "Wilson",
    username: "alexw2020",
    gender: "female",
    dob: "1998-01-31",
    email: "alexandra.wilson@example.com",
    password: "password_secure!",
    role: "guest",
  },
];

export const demoLocations = [
  {
    city: "Charleroi",
    country: "Belgium",
    state: "Wallonie",
    postalCode: "6042",
    phone: "393-383-9565",
    venueName: "Cormier, Friesen and Breitenberg",
  },
  {
    city: "Lezhu",
    country: "China",
    state: "a4m4j8pb",
    postalCode: "a4m4j8pb",
    phone: "280-324-0861",
    venueName: "Stanton and Sons",
  },
  {
    city: "Abovyan",
    country: "Armenia",
    state: "b4r4u2nl",
    postalCode: "b4r4u2nl",
    phone: "208-549-5935",
    venueName: "Robel, Feeney and Ullrich",
  },
  {
    city: "Atar",
    country: "Mauritania",
    state: "5skmst0p",
    postalCode: "5skmst0p",
    phone: "203-511-7046",
    venueName: "Parker, Kuhlman and Kunde",
  },
  {
    city: "Guanyinsi",
    country: "China",
    state: "4yxb8vnq",
    postalCode: "4yxb8vnq",
    phone: "482-492-5780",
    venueName: "Carter Inc",
  },
  {
    city: "Kubang",
    country: "Indonesia",
    state: "m6g2sje5",
    postalCode: "m6g2sje5",
    phone: "217-492-5647",
    venueName: "Kautzer, Rau and Jast",
  },
  {
    city: "Tuochuan",
    country: "China",
    state: "1z3i1ygm",
    postalCode: "1z3i1ygm",
    phone: "607-406-5073",
    venueName: "Koelpin, Kiehn and Lesch",
  },
  {
    city: "Venda",
    country: "Portugal",
    state: "Braga",
    postalCode: "4715-529",
    phone: "146-423-1016",
    venueName: "Blick, Heidenreich and Corwin",
  },
  {
    city: "Ribamar",
    country: "Portugal",
    state: "Lisboa",
    postalCode: "2530-631",
    phone: "932-678-4617",
    venueName: "Erdman LLC",
  },
  {
    city: "Injīl",
    country: "Afghanistan",
    state: "wv2f1gpe",
    postalCode: "wv2f1gpe",
    phone: "326-830-0997",
    venueName: "Ruecker, Wunsch and Green",
  },
];

export const demoCategories = [
  {
    name: "Music & Concerts",
    slug: "music-concerts",
  },
  {
    name: "Sports & Fitness",
    slug: "sports-fitness",
  },
  {
    name: "Conferences & Webinars",
    slug: "conferences-webinars",
  },
  {
    name: "Workshops & Training",
    slug: "workshops-training",
  },
  {
    name: "Art & Culture",
    slug: "art-culture",
  },
  {
    name: "Food & Drink",
    slug: "food-drink",
  },
  {
    name: "Festivals & Fairs",
    slug: "festivals-fairs",
  },
  {
    name: "Networking & Meetups",
    slug: "networking-meetups",
  },
  {
    name: "Charity & Fundraising",
    slug: "charity-fundraising",
  },
  {
    name: "Theater & Performances",
    slug: "theater-performances",
  },
  {
    name: "Travel & Adventure",
    slug: "travel-adventure",
  },
  {
    name: "Technology & Innovation",
    slug: "technology-innovation",
  },
  {
    name: "Business & Startups",
    slug: "business-startups",
  },
  {
    name: "Family & Kids",
    slug: "family-kids",
  },
  {
    name: "Health & Wellness",
    slug: "health-wellness",
  },
  {
    name: "Lifestyle & Hobbies",
    slug: "lifestyle-hobbies",
  },
  {
    name: "Education & Learning",
    slug: "education-learning",
  },
  {
    name: "Religious & Spiritual",
    slug: "religious-spiritual",
  },
  {
    name: "Seasonal Events",
    slug: "seasonal-events",
  },
  {
    name: "Public Services & Government",
    slug: "public-services-government",
  },
];


